### ISSUE TITLE
about the artile "Doctrine Second Level Cache with Translations and Redis"

### ISSUE THREAD

**Issue by lcp0578** [kunicmarko20/kunicmarko20.github.io#3]
I learned more form you article.
but, i have some questions?can you help me? thanks!

about Doctrine Second Level Cache and DoctrineCacheBundle? What did they do separately?
i want use DoctrineCacheBundle for type predis, Can you write a document about it?

thanks again

**Comment by lcp0578** [comment]
i got an error, 
Second level cache does not support scalar results.

**Comment by lcp0578** [comment]
i got it

**Comment by kunicmarko20** [comment]
Hi,

sorry for not replying but I just now got the notification on GitHub.

Happy to hear that you solved your problems.

**Comment by lcp0578** [comment]
thx
